---
json_rpc_url: "http://api.devnet.solana.com"
update_manifest_pubkey:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
current_update_manifest: ~
update_poll_secs: 3600
explicit_release:
  Channel: stable
releases_dir: /Users/thehesoyam/.local/share/solana/install/releases
active_release_dir: /Users/thehesoyam/.local/share/solana/install/active_release
